image: maven:latest

stages:
 - test 
 - deploy
 
maven_test:
  stage: test
  tags: 
    - maven
  script:
    - mvn test -Dmaven.test.skip=true

maven_deploy:
  stage: deploy
  tags:
    - maven
    - artifactory
  before_script:
    #SSH agent
    - 'which ssh-agent || ( apk update  && apk add openssh)'
    - eval $(ssh-agent -s)    
    - ssh-add <(echo "$SSH_PRIVATE_KEY")    
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    #GPG (gnupg)
    - 'which gpg-agent || ( apk update  && apk add gnupg)'
    - gpg -v --batch --import <(echo "$GPG_PRIVATE_KEY")
    # Install JFrog CLI / configure artifactory
    -  curl -fL https://getcli.jfrog.io | sh
    - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS
    - ./jfrog rt c show
    - export M2_HOME=/usr/share/maven
    - sed -i 's,SNAPSHOT_REPO_KEY,'"$SNAPSHOT_REPO_KEY"',g' configuration.yml
    - sed -i 's,RELEASE_REPO_KEY,'"$RELEASE_REPO_KEY"',g' configuration.yml
    - sed -i 's,ARTIFACTORY_JCENTER_REPO_KEY,'"$ARTIFACTORY_JCENTER_REPO_KEY"',g' configuration.yml
  script:
    - ./jfrog rt mvn "clean verify gpg:sign install -Dmaven.test.skip=true -DadditionalJOption=-Xdoclint:none" configuration.yml --build-name=jecoli_gitlabci_build --build-number=$CI_JOB_ID
    - ./jfrog rt jecoli_gitlabci_build $CI_JOB_ID
    - ./jfrog rt jecoli_gitlabci_build $CI_JOB_ID
  only:
    - master