language: java
cache:
  directories:
    - $HOME/.gradle/caches/
    
script: echo "do not make tests"

deploy:
    provider: script
    script:
        - build/deploy.sh $TRAVIS_BRANCH
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^dev|master$
